#!/bin/bash
echo -e "Are you sure you want to delete all non-default audio files? This action cannot be undone.\nType 'Yes, please' to confirm"
read confirm_code
if [ "$confirm_code" == "Yes, please" ]; then
    rm ./src/services/data/audio/audio_*
else
    echo "Cancelling operation"
fi